routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('menu');
});

route::get('/menu', 'PagesController@index')->name('menu');
route::get('/beranda', 'PagesController@beranda')->name('beranda');
Route::get('/detailbuku', 'PagesController@detail')->name('detailbuku');
Route::get('/buku/setKategori', 'PagesController@setKategori')->name('setKategori');
Route::get('/detailbuku/{id}','PagesController@show')->name('show');
Route::get('/sisa','PagesController@sisa')->name('sisa');

route::get('/buku', 'PagesController@buku')->name('buku');

Route::resource('/pages', 'PagesController');
Route::get('/buku/cari','PagesController@cari')->name('cari');
Route::get('/info','PagesController@info')->name('info');
Route::get('/buku/kategori','PagesController@kategori')->name('kategori');
Route::get('/userguide','PagesController@guide')->name('guide');

Route::get('/laporan/cari','TransaksiController@cari')->name('cari');

Auth::routes();
route::get('logout', 'Auth\LoginController@logout')->name('logout');
route::get('/admin/user', 'Admin\UserController@create')->name('register');
route::post('/auth/login', 'RegisterController@store')->name('registerPost');
route::get('/auth/regis', 'Auth\LoginController@register')->name('regis');

Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::patch('profile', 'ProfileController@update')->name('profile.update');
});

route::middleware('admin')->group(function () {
    route::get('/home', 'HomeController@index')->name('home');
    route::get('/histori', 'TransaksiController@histori')->name('histori');

    route::get('/laporanpengembalian/periode', 'TransaksiController@periodepengembalian')->name('periode_awal');
    route::get('/laporan/periode', 'TransaksiController@periodepinjam')->name('periode_awal');

    // ASC & DESC
    route::get('/laporan/dataterbaru', 'TransaksiController@baru')->name('baru');
    route::get('/laporan/dataterlama', 'TransaksiController@lama')->name('lama');
    route::get('/histori/dataterbaru', 'TransaksiController@databaru')->name('baru');
    route::get('/histori/dataterlama', 'TransaksiController@datalama')->name('lama');

    // Filter Laporan
    route::get('/pinjam', 'TransaksiController@pinjam')->name('pinjam');
    route::get('/cetaklaporan', 'TransaksiController@cetakLaporan')->name('cetaklaporan');
    route::get('/cetaklaporanpertanggal/{tglawal}/{tglakhir}', 'TransaksiController@cetakLaporanPertanggal')->name('cetaklaporanpertanggal');
    Route::get('/laporan/periode','Transaksicontroller@periode')->name('periode');


    Route::prefix('acl')->name('acl.')->group(function () {
        Route::get('permission', 'Admin\ACLController@permissionList')->name('permission.index');
        Route::get('permission/data', 'Admin\ACLController@permissionData')->name('permission.data');
        Route::prefix('role')->name('role.')->group(function () {
            Route::get('/', 'Admin\ACLController@roleList')->name('index');
            Route::get('/data', 'Admin\ACLController@roleData')->name('data');
            Route::get('/create', 'Admin\ACLController@createRole')->name('create');
            Route::post('/create', 'Admin\ACLController@storeRole')->name('store');
            Route::get('/{id}/edit', 'Admin\ACLController@editRole')->name('edit');
            Route::patch('/{id}/edit', 'Admin\ACLController@updateRole')->name('update');
            Route::delete('/{id}/destroy', 'Admin\ACLController@deleteRole')->name('destroy');
        });
    });

    // Users
    route::resource('/users', 'Admin\UserController');
    route::get('/users/data/json', 'Admin\UserController@getData')->name('users.data');

    // Buku
    Route::resource('/buku', 'BukuController');
    Route::get('/buku/data/json', 'BukuController@getData')->name('buku.data');
    Route::post('/buku/data/json', 'BukuController@imageUploadPost')->name('image.upload.post');
    Route::post('/buku/data/json', 'BukuController@bacaUploadPost')->name('baca.upload.post');
    Route::get('/cetak-buku', 'BukuController@cetak')->name('cetak-buku');

    // Anggota
    Route::resource('/anggota', 'AnggotaController');
    Route::get('/anggota/data/json', 'AnggotaController@getData')->name('anggota.data');
    Route::get('/cetak-anggota', 'AnggotaController@cetak')->name('cetak-anggota');

    // Kategori
    Route::resource('/kategori', 'KategoriController');
    Route::get('/kategori/data/json', 'KategoriController@getData')->name('kategori.data');

    // Transaksi
    Route::resource('/transaksi', 'TransaksiController');
    Route::get('/transaksi/data/json', 'TransaksiController@getData')->name('transaksi.data');
    Route::get('/cetak-transaksi', 'TransaksiController@cetak')->name('cetak-transaksi');

});

Route::get('check/accessor', function (App\Models\Transaksi $id) {
    $data = new \App\Models\Transaksi;
    dd($data->first()->getBorrowDateAttribute());
});

app/Models/Buku.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Buku extends Model
{
    use SoftDeletes;

    public $guarded = ['id'];
    public $timestamps = false;
    
    protected $fillable = [
        'kode',
        'penerbit',
        'penulis',
        'judul',
        'sinopsis',
        'penulis',
        'kategori_id',
        'jumlah_buku',
        'thn_terbit',
        'cover_buku',
        'baca_buku',
        'kondisi',
    ];

    /**
     * Get formatted ID.
     *
     * @return string
     */
    public function getFormattedIdAttribute()
    {
        return '#' . $this->attributes['id'];
    }

    /**
     * Upload file and save path to database.
     *
     * @param UploadedFile $file
     * 
     * @return void
     */

    public static function boot()
    {
        parent::boot();

        static::created(function($model) {
            $model->kode = 'B8K'.Carbon::now()->format('YmdHms').$model->id;
            $model->save();
        });
    }
    
    public function setCoverBukuAttribute($cover_buku)
    {
        if (is_null($cover_buku)) {
            return;
        }

        $path = 'assets/buku/cover';

        //Delete on update
        if (!is_null($this->getAttribute('cover_buku'))) {
            \Storage::disk(config('app.disk_system'))->delete($this->getAttribute('cover_buku'));
        }

        $this->attributes['cover_buku'] = \Storage::disk(config('app.disk_system'))->put($path, $cover_buku);
    }

    /**
     * Get file URL.
     *
     * @return string
     */
    public function getCoverBukuUrlAttribute()
    {
        if (is_null($this->getAttribute('cover_buku'))) {
            return null;
        }

        return 'http://127.0.0.1:8000/storage/' . $this->getAttribute('cover_buku');
    }

    public function setBacaBukuAttribute($baca_buku)
    {
        if (is_null($baca_buku)) {
            return;
        }

        $path = 'assets/buku/naskah';

        //Delete on update
        if (!is_null($this->getAttribute('baca_buku'))) {
            \Storage::disk(config('app.disk_system'))->delete($this->getAttribute('baca_buku'));
        }

        $this->attributes['baca_buku'] = \Storage::disk(config('app.disk_system'))->put($path, $baca_buku);
    }

    /**
     * Get file URL.
     *
     * @return string
     */
    public function getBacaBukuUrlAttribute()
    {
        if (is_null($this->getAttribute('baca_buku'))) {
            return null;
        }

        return 'http://127.0.0.1:8000/storage/' . $this->getAttribute('baca_buku');
    }

    public function transaksi()
    {
        return $this->hasMany(\App\Models\Transaksi::class);
    }

    public function denda()
    {
        return $this->hasMany(\App\Denda::class);
    }

    public function kategori()
    {
        return $this->belongsTo(\App\Kategori::class, 'kategori_id', 'id');
    }

    /**
     * Get Judul Buku
     * 
     * @return string
     */
    public function getKategoriNameAttribute()
    {
        // return optional($this->kategori())->first('nama');

        $kategori = $this->kategori()->first(['nama']);

        if (!is_null($kategori)) {
            return $kategori->nama;
        }

        return '-';
    }

    public function filter($kategori)
    {
        return $this->table('bukus')
        ->like('kategoris', $kategori)
        ->join('kategoris', 'kategoris.kategori_id = bukus.kategori_id')
        ->findAll();
    }
}

app/Models/Transaksi.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transaksi extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'kode',
        // 'kode_buku',
        'buku_id',
        'user_id',
        // 'kode_anggota',
        'anggota_id',
        'tgl_pinjam',
        'tgl_hrs_kembali',
        'tgl_pengembalian',
    ];

    /**
     * Get formatted ID.
     *
     * @return string
     */
    public function getFormattedIdAttribute()
    {
        return '#' . $this->attributes['id'];
    }

    public static function boot()
    {
        parent::boot();

        static::created(function($model) {
            $model->kode = 'TR'.Carbon::now()->format('YmdHms').$model->id;
            $model->save();
        });
    }

    /**
     * Relation to anggota
     *
     * @return BelongsTo
     */
    public function anggota()
    {
        return $this->belongsTo(\App\Models\Anggota::class, 'anggota_id', 'id');
    }

    
    /**
     * Get Nama Anggota
     * 
     * @return string
     */
    public function getAnggotaNameAttribute()
    {
        // return optional($this->anggota()->first('nama'))->first();
        $anggota = $this->anggota()->first(['name']);
        
        if (!is_null($anggota)) {
            return $anggota->name;
        }
        
        return '-';
    }

    /**
     * Relation to buku
     *
     * @return BelongsTo
     */
    public function buku()
    {
        return $this->belongsTo(\App\Models\Buku::class, 'buku_id', 'id');
    }

    /**
     * Get Judul Buku
     * 
     * @return string
     */
    public function getBukuNameAttribute()
    {
        // return optional($this->buku())->first('judul');

        $buku = $this->buku()->first(['judul']);

        if (!is_null($buku)) {
            return $buku->judul;
        }

        return '-';
    }

    /**
     * Get Return Date
     * 
     * @return string
     */
    public function getReturnDateAttribute()
    {
        $now = Carbon::now();
        if ($now->format('Y-m-d') > $this->getAttribute('tgl_hrs_kembali')) {
            return '<div class="chip chip-' . 'danger' . '">
                    <div class="chip-body"><div class="chip-text">' . 
                    $this->getAttribute('tgl_hrs_kembali') . 
                    '</div></div></div>';
        }

        return $this->getAttribute('tgl_hrs_kembali');
    }

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }

    public function getUserNameAttribute()
    {
        // return optional($this->anggota()->first('nama'))->first();
        $user = $this->user()->first(['name']);
        
        if (!is_null($user)) {
            return $user->name;
        }
        
        return '-';
    }

}

resources/views/beranda.blade.php
@extends('layouts.nav', [
'title' => 'Laporan Pengembalian',
'breadcrumbs' => [
'Laporan Pengembalian'
],
])

@section('content')
<br>
<br>
<br>
<div class="container-lg">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header d-flex flex-column align-items-start pb-0">
                    <div class="avatar bg-rgba-primary p-50 m-0">
                        <div class="user-content">
                            <i class="feather icon-book-open text-primary font-medium-5" button title="Jumlah Buku"></i>
                        </div>
                    </div>
                    <h2 class="text-bold-700 mt-1">{{ $buku }}</h2>
                    <p class="mb-100">Total Buku</p>
                    <br>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card">
                <div class="card-header d-flex flex-column align-items-start pb-0">
                    <div class="avatar bg-rgba-primary p-50 m-0">
                        <div class="user-content">
                            <i class="feather icon-book-open text-primary font-medium-5" button title="Jumlah Buku"></i>
                        </div>
                    </div>
                    <h2 class="text-bold-700 mt-1">{{ $ck }}</h2>
                    <p class="mb-100">Total Kategori</p>
                    <br>
                </div>
            </div>
        </div>
        
        @foreach($kategori as $k)
        <div class="col-md-3">
            <div class="card">
                <div class="card-header d-flex flex-column align-items-start pb-0">
                    <div class="avatar bg-rgba-primary p-50 m-0">
                        <div class="user-content">
                            <i class="feather icon-book-open text-primary font-medium-5" button title="Jumlah Buku"></i>
                        </div>
                    </div>
                    <h2 class="text-bold-700 mt-1">{{ $k->nama }}</h2>
                    <p class="mb-100"></p>
                    <br>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
<footer class="footer footer-static footer-dark footer-fixed">
    <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25"><strong>Copyright</strong> MyLibrary &copy; {{ date('Y') }}</span>
        <button class="btn btn-primary btn-icon scroll-top" type="button"><i class="feather icon-arrow-up"></i></button>
    </p>
</footer>
@endsection

resources/views/cetaklaporan.blade.php
@extends('layouts.app', [
'title' => 'Cetak Laporan Pertanggal',
'breadcrumbs' => [
'Laporan',
'Cetak Laporan Pertanggal'
],
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">
            <h2>Cetak Laporan Pertanggal</h2>
            Tanggal Awal
            <div class="input-group mb-3">
                <input type="date" name="tglawal" id="tglawal" class="form-control" required>
            </div>
            Tanggal Akhir
            <div class="input-group mb-3">
                <input type="date" name="tglakhir" id="tglakhir" class="form-control" required>
            </div>
            <div class="input-group mb-3">
            <a href="" onclick="this.href='/cetaklaporanpertanggal/'+ document.getElementById('tglawal').value + '/' + document.getElementById('tglakhir').value " target="_blank" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
// AJAX DataTable
$('.dataTable').DataTable({
    processing: true,
    serverSide: true,
    ordering: false,
});
</script>
@endpush

resources/views/detailbuku.blade.php
@extends('layouts.nav')

@section('content')
<br>
<div class="container-md">
  <button onclick="goBack()" class="badge bg-info">Kembali</button>
  <script>
      function goBack() {
          window.history.back();
      }
  </script>
</div>
<br>
<div class="container-md">
  <div class="row">
    <br>
    <div class="card mb-5" style="max-width: 1300px;">
        <div class="row g-0">
          <div class="col-md-4">
            <br>
            <img src="{{ \Storage::url($buku->cover_buku) }}" class="img-fluid rounded-start" alt="...">
          </div>
          	<div class="col-md-8">
            	<div class="card-body">
					<h1 class="card-title">{{$buku->judul}}</h1>
						<p class="card-text"><b> Sinopsis : </b>{{$buku->sinopsis}}</p>
						<hr>
						<h3>Detail Buku</h3>
							<p class="card-text"><b> Penerbit : </b> {{$buku->penerbit}}</p>
							<p class="card-text"><b> Penulis : </b> {{$buku->penulis}}</p>
							<p class="card-text"><b> Kategori : </b> {{$buku->kategori->nama}}</p>
							<p class="card-text"><b> Tahun Terbit : </b> {{$buku->thn_terbit}}</p>
							<p class="card-text"><b> Yang Tersedia di Perpustakaan : </b> {{$buku->jumlah_buku}}</p>
							@if (Auth::guest())
							<p><a href="{{ route('login') }}" class="btn btn-success">Pinjam</a></p>
							@else
							@if (!is_null($buku->baca_buku_url)) 
							<a href="{{$buku->baca_buku_url}}" class="btn btn-success">Download Buku {{$buku->judul}}</a>
							@else
							<!-- Button trigger modal -->
							<button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#bacaBuku">
								Baca
							</button>

							<!-- Modal -->
							<div class="modal fade" id="bacaBuku" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="exampleModalLabel">My Library</h5>
											<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
										</div>
										<div class="modal-body">
											Datanglah Ke Perpustakaan Untuk Meminjam Buku Ini!
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-primary" data-bs-dismiss="modal">Oke</button>
										</div>
									</div>
								</div>
							</div>
							@endif
						@endif
              	</div>
            </div>
        </div>
          <br>
    </div>
  </div>
</div>
@endsection

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
// AJAX DataTable
$('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    ajax: {
        url: '{!! route('buku.data',) !!}',
    },
    ordering: false,
    columns: [
        { data: 'formatted_id', name: 'formatted_id' },
        { data: 'kode', name: 'kode' },
        { data: 'judul', name: 'judul' },
        { data: 'kategori_name', name: 'kategori_id' },
        { data: 'cover_buku_url', name: 'cover_buku_url' },
        { data: 'baca_buku_url', name: 'baca_buku_url' },
        { data: 'jumlah_buku', name: 'jumlah_buku' },
        { data: 'action', name: 'action' },
    ],
});

</script>
@endpush

resources/views/home.blade.php
@extends('layouts.app', [
'title' => 'Dashboard',
'breadcrumbs' => [
'Dashboard' 
],
])

@section('content')
<section id="dashboard-analytics">

<div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header d-flex flex-column align-items-start pb-0">
                    <div class="avatar bg-rgba-primary p-50 m-0">
                        <div class="user-content">
                            <i class="feather icon-list text-primary font-medium-5" button title="Sedang Dipinjam"></i>
                        </div>
                    </div>
                    <h2 class="text-bold-700 mt-1">{{ $transaksi }}</h2>
                    <p class="mb-100">Sedang Dipinjam</p>
                    <br>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card">
                <div class="card-header d-flex flex-column align-items-start pb-0">
                        <div class="avatar bg-rgba-primary p-50 m-0">
                            <div class="user-content">
                                <i class="feather icon-book-open text-primary font-medium-5" button title="Jumlah Buku"></i>
                            </div>
                        </div>
                        <h2 class="text-bold-700 mt-1">{{ $buku }}</h2>
                        <p class="mb-100">Total Buku</p>
                    <br>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card">
                <div class="card-header d-flex flex-column align-items-start pb-0">
                    <div class="avatar bg-rgba-primary p-50 m-0">
                        <div class="user-content">
                            <i class="feather icon-users text-primary font-medium-5" button title="Jumlah Anggota"></i>
                        </div>
                    </div>
                    <h2 class="text-bold-700 mt-1">{{ $anggota }}</h2>
                    <p class="mb-100">Jumlah Anggota</p>
                    <br>
                </div>
            </div>
        </div>

        @if (auth()->user()->name == "Admin")
        <div class="col-md-3">
            <div class="card">
                <div class="card-header d-flex flex-column align-items-start pb-0">
                    <div class="avatar bg-rgba-primary p-50 m-0">
                        <div class="user-content">
                            <i class="feather icon-layers text-primary font-medium-5" button title="Total User"></i>
                        </div>
                    </div>
                    <h2 class="text-bold-700 mt-1">{{ $user }}</h2>
                    <p class="mb-100">Jumlah User</p>
                    <br>
                </div>
            </div>
        </div>
        @endif

</div>
</section>
@endsection

resources/views/info.blade.php
@extends('layouts.nav')

@section('content')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/info.css') }}">
<link id="favicon" rel="shortcut icon" type="image/png" href="{{ asset('public/img/scan.png') }}">

<div class="co">
    <div class="content">
        <div class="bc">
            <div class="kiri">
                <div class="title">Cara scan User Guide di Handphone Anda:</div>
                    <ol class="_1TxZR">
                        <p class="_1Fl07">1. Buka Aplikasi Scan di telepon Anda</p>
                        <p class="_1Fl07">2. Arahkan telepon Anda ke layar ini untuk memindai kode tersebut</p>
                    </ol>
                </div>
            <div class="kanan">
                <img src="/img/scan.png">
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/menu.blade.php
@extends('layouts.nav')

@section('content')
@csrf
<br>
<div class="container-lg">
  <div class="row">
    <br>
    <table id="table" class="display" style="width:100%">
      <tbody>
        @foreach($buku as $b)
        <div class="col-md-3" style="max-width: 50rem;">
          <div class="card mb-3 shadow-lg">
            <br>
            @if($b->cover_buku != null)
            <img src="{{ \Storage::url($b->cover_buku) }}" style="width: 130px;margin-left: auto;margin-right: auto;height: 170px;" class="card-img-top">
            @endif
            <hr>
            <div class="card-body">
              <h6>{{ $b->penulis }}</h6>
              <h4><b>{{ $b->judul }}</b></h4>
              @if (Auth::guest())
              <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#loginModal">
                Detail
              </button>

              <!-- Modal -->
              <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">My Library</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Anda Harus Login Terlebih Dahulu Untuk Melihat Detail Buku!
                    </div>
                    <div class="modal-footer">
                      <p><a href="{{ route('login') }}" class="btn btn-warning">Login Sekarang!</a></p>
                    </div>
                  </div>
                </div>
              </div>
              @else
              <!-- <p><a href="{{ route('buku.index') }}" class="btn btn-success">Pinjam / Baca</a></p> -->

              <p><a href="/detailbuku/{{$b->id}}" class="btn btn-success">Detail </a></p>
              @endif
            </div>
          </div>
        </div>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

<button onclick="topFunction()" id="scroll-btn" title="Top"><i class="feather icon-arrow-up"></i></button>

<script>
  window.onscroll = function() {
    scrollFunction()
  };

  function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
      document.getElementById("scroll-btn").style.display = "block";
    } else {
      document.getElementById("scroll-btn").style.display = "none";
    }
  }

  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>

<footer class="footer footer-static footer-dark">
  <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25"><strong>Copyright</strong> MyLibrary &copy; {{ date('Y') }}</span>
    <button class="btn btn-primary btn-icon scroll-top" type="button"><i class="feather icon-arrow-up"></i></button>
  </p>
</footer>


<script src="{{ asset('public/assets/js/jquery-3.4.0.min.js') }}"></script>
<script src="{{ asset('public/assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('public/assets/js/filter.js') }}"></script>

@endsection

resources/views/pinjam.blade.php
@extends('layouts.app', [
'title' => 'Laporan Peminjaman',
'breadcrumbs' => [
'Laporan',
'Laporan Peminjaman'
],
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">
            <div class="row">
                
                <a href="{{ route('cetaklaporan') }}" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
                <div class="col-md-3">
                    <div class="dropdown">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Urut Berdasarkan</button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ url('laporan/dataterbaru') }}"><i class="feather icon-chevrons-up"></i>Data Terbaru</a>
                            <a class="dropdown-item" href="{{ url('laporan/dataterlama') }}"><i class="feather icon-chevrons-down"></i> Data Terlama</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover" id="dataTable">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Kode Transaksi</th>
                            <th scope="col">Judul Buku</th>
                            <th scope="col">Nama Anggota</th>
                            <th scope="col">Tgl Peminjaman</th>
                            <th scope="col">Batas Waktu Peminjaman</th>
                            <th scope="col">Tgl Pengembalian</th>
                        </tr>
                    </thead>
                    <tbody id="dataTable">
                        @php
                        $no = 0;
                        @endphp
                        @foreach ($data as $dataa)
                        <tr>
                            <th scope="row">{{ ++$no }}</th>
                            <td>{{ $dataa->kode }}</td>
                            <td>{{ $dataa->buku_name }}</td>
                            <td>{{ $dataa->user_name }}</td>
                            <td>{{ date('d F Y', strtotime($dataa->tgl_pinjam)) }}</td>
                            <td>{{ date('d F Y', strtotime($dataa->tgl_hrs_kembali)) }}</td>
                            @if($dataa->deleted_at == null)
                            <td class="badge bg-warning">Belum Dikembalikan!</td>
                            @else
                            <td class="badge bg-success">{{ date('d F Y', strtotime($dataa->deleted_at)) }}</td>
                            @endif
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
// AJAX DataTable
$('.dataTable').DataTable({
    processing: true,
    serverSide: true,
    ordering: false,
});
</script>
@endpush