routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('menu');
});

route::get('/menu', 'PagesController@index')->name('menu');
route::get('/beranda', 'PagesController@beranda')->name('beranda');
Route::get('/detailbuku', 'PagesController@detail')->name('detailbuku');
Route::get('/buku/setKategori', 'PagesController@setKategori')->name('setKategori');
Route::get('/detailbuku/{id}','PagesController@show')->name('show');
Route::get('/sisa','PagesController@sisa')->name('sisa');

route::get('/buku', 'PagesController@buku')->name('buku');

Route::resource('/pages', 'PagesController');
Route::get('/buku/cari','PagesController@cari')->name('cari');
Route::get('/info','PagesController@info')->name('info');
Route::get('/buku/kategori','PagesController@kategori')->name('kategori');
Route::get('/userguide','PagesController@guide')->name('guide');

Route::get('/laporan/cari','TransaksiController@cari')->name('cari');

Auth::routes();
route::get('logout', 'Auth\LoginController@logout')->name('logout');
route::get('/admin/user', 'Admin\UserController@create')->name('register');
route::post('/auth/login', 'RegisterController@store')->name('registerPost');
route::get('/auth/regis', 'Auth\LoginController@register')->name('regis');

Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::patch('profile', 'ProfileController@update')->name('profile.update');
});

route::middleware('admin')->group(function () {
    route::get('/home', 'HomeController@index')->name('home');
    route::get('/histori', 'TransaksiController@histori')->name('histori');

    route::get('/laporanpengembalian/periode', 'TransaksiController@periodepengembalian')->name('periode_awal');
    route::get('/laporan/periode', 'TransaksiController@periodepinjam')->name('periode_awal');

    // ASC & DESC
    route::get('/laporan/dataterbaru', 'TransaksiController@baru')->name('baru');
    route::get('/laporan/dataterlama', 'TransaksiController@lama')->name('lama');
    route::get('/histori/dataterbaru', 'TransaksiController@databaru')->name('baru');
    route::get('/histori/dataterlama', 'TransaksiController@datalama')->name('lama');

    // Filter Laporan
    route::get('/pinjam', 'TransaksiController@pinjam')->name('pinjam');
    route::get('/cetaklaporan', 'TransaksiController@cetakLaporan')->name('cetaklaporan');
    route::get('/cetaklaporanpertanggal/{tglawal}/{tglakhir}', 'TransaksiController@cetakLaporanPertanggal')->name('cetaklaporanpertanggal');
    Route::get('/laporan/periode','Transaksicontroller@periode')->name('periode');


    Route::prefix('acl')->name('acl.')->group(function () {
        Route::get('permission', 'Admin\ACLController@permissionList')->name('permission.index');
        Route::get('permission/data', 'Admin\ACLController@permissionData')->name('permission.data');
        Route::prefix('role')->name('role.')->group(function () {
            Route::get('/', 'Admin\ACLController@roleList')->name('index');
            Route::get('/data', 'Admin\ACLController@roleData')->name('data');
            Route::get('/create', 'Admin\ACLController@createRole')->name('create');
            Route::post('/create', 'Admin\ACLController@storeRole')->name('store');
            Route::get('/{id}/edit', 'Admin\ACLController@editRole')->name('edit');
            Route::patch('/{id}/edit', 'Admin\ACLController@updateRole')->name('update');
            Route::delete('/{id}/destroy', 'Admin\ACLController@deleteRole')->name('destroy');
        });
    });

    // Users
    route::resource('/users', 'Admin\UserController');
    route::get('/users/data/json', 'Admin\UserController@getData')->name('users.data');

    // Buku
    Route::resource('/buku', 'BukuController');
    Route::get('/buku/data/json', 'BukuController@getData')->name('buku.data');
    Route::post('/buku/data/json', 'BukuController@imageUploadPost')->name('image.upload.post');
    Route::post('/buku/data/json', 'BukuController@bacaUploadPost')->name('baca.upload.post');
    Route::get('/cetak-buku', 'BukuController@cetak')->name('cetak-buku');

    // Anggota
    Route::resource('/anggota', 'AnggotaController');
    Route::get('/anggota/data/json', 'AnggotaController@getData')->name('anggota.data');
    Route::get('/cetak-anggota', 'AnggotaController@cetak')->name('cetak-anggota');

    // Kategori
    Route::resource('/kategori', 'KategoriController');
    Route::get('/kategori/data/json', 'KategoriController@getData')->name('kategori.data');

    // Transaksi
    Route::resource('/transaksi', 'TransaksiController');
    Route::get('/transaksi/data/json', 'TransaksiController@getData')->name('transaksi.data');
    Route::get('/cetak-transaksi', 'TransaksiController@cetak')->name('cetak-transaksi');

});

Route::get('check/accessor', function (App\Models\Transaksi $id) {
    $data = new \App\Models\Transaksi;
    dd($data->first()->getBorrowDateAttribute());
});

app/Models/Buku.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Buku extends Model
{
    use SoftDeletes;

    public $guarded = ['id'];
    public $timestamps = false;
    
    protected $fillable = [
        'kode',
        'penerbit',
        'penulis',
        'judul',
        'sinopsis',
        'penulis',
        'kategori_id',
        'jumlah_buku',
        'thn_terbit',
        'cover_buku',
        'baca_buku',
        'kondisi',
    ];

    /**
     * Get formatted ID.
     *
     * @return string
     */
    public function getFormattedIdAttribute()
    {
        return '#' . $this->attributes['id'];
    }

    /**
     * Upload file and save path to database.
     *
     * @param UploadedFile $file
     * 
     * @return void
     */

    public static function boot()
    {
        parent::boot();

        static::created(function($model) {
            $model->kode = 'B8K'.Carbon::now()->format('YmdHms').$model->id;
            $model->save();
        });
    }
    
    public function setCoverBukuAttribute($cover_buku)
    {
        if (is_null($cover_buku)) {
            return;
        }

        $path = 'assets/buku/cover';

        //Delete on update
        if (!is_null($this->getAttribute('cover_buku'))) {
            \Storage::disk(config('app.disk_system'))->delete($this->getAttribute('cover_buku'));
        }

        $this->attributes['cover_buku'] = \Storage::disk(config('app.disk_system'))->put($path, $cover_buku);
    }

    /**
     * Get file URL.
     *
     * @return string
     */
    public function getCoverBukuUrlAttribute()
    {
        if (is_null($this->getAttribute('cover_buku'))) {
            return null;
        }

        return 'http://127.0.0.1:8000/storage/' . $this->getAttribute('cover_buku');
    }

    public function setBacaBukuAttribute($baca_buku)
    {
        if (is_null($baca_buku)) {
            return;
        }

        $path = 'assets/buku/naskah';

        //Delete on update
        if (!is_null($this->getAttribute('baca_buku'))) {
            \Storage::disk(config('app.disk_system'))->delete($this->getAttribute('baca_buku'));
        }

        $this->attributes['baca_buku'] = \Storage::disk(config('app.disk_system'))->put($path, $baca_buku);
    }

    /**
     * Get file URL.
     *
     * @return string
     */
    public function getBacaBukuUrlAttribute()
    {
        if (is_null($this->getAttribute('baca_buku'))) {
            return null;
        }

        return 'http://127.0.0.1:8000/storage/' . $this->getAttribute('baca_buku');
    }

    public function transaksi()
    {
        return $this->hasMany(\App\Models\Transaksi::class);
    }

    public function denda()
    {
        return $this->hasMany(\App\Denda::class);
    }

    public function kategori()
    {
        return $this->belongsTo(\App\Kategori::class, 'kategori_id', 'id');
    }

    /**
     * Get Judul Buku
     * 
     * @return string
     */
    public function getKategoriNameAttribute()
    {
        // return optional($this->kategori())->first('nama');

        $kategori = $this->kategori()->first(['nama']);

        if (!is_null($kategori)) {
            return $kategori->nama;
        }

        return '-';
    }

    public function filter($kategori)
    {
        return $this->table('bukus')
        ->like('kategoris', $kategori)
        ->join('kategoris', 'kategoris.kategori_id = bukus.kategori_id')
        ->findAll();
    }
}

resources/views/Book/cetak-buku.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <style>
        table.static {
            position: relative;
            border: 1px solid #543535;
        }
    </style>
    <title>Cetak Data Buku</title>
</head>
<body>
    <div class="form-group">
        <div class="container">
            <div class="row">
                <center><img src="/img/logo.png" style="max-width: 150px;" class="inline"></center>
                <center><img src="/img/logo1.jpeg" style="max-width: 150px;" class="inline"></center>
            </div>
        </div>
        <hr>
        <h3><center>Data Buku</center></h3>
        <table class="static" align="center" rules="all" border="1px" style="width: 95%;">
            <tr>
                <th>No</th>
                <th>Kode Buku</th>
                <th>Judul</th>
                <th>Penerbit</th>
                <th>Penulis</th>
                <th>Kategori</th>
                <th>Tahun Terbit</th>
            </tr>
            @foreach($data as $data)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $data->kode }}</td>
                <td>{{ $data->judul }}</td>
                <td>{{ $data->penerbit }}</td> 
                <td>{{ $data->penulis }}</td> 
                <td>{{ $data->kategori->nama }}</td>
                <td>{{ $data->thn_terbit }}</td>
            </tr>
            @endforeach
        </table>
    </div>
    <br>
        <br>

    <script type="text/javascript">
    window.print();
    
    </script>

    <div class="container" style="text-align: right;">
        <p>Bandung,<span id="tanggalwaktu"></span></p>
        <br><br>
        <script>
            var tw = new Date();
            if (tw.getTimezoneOffset() == 0) (a=tw.getTime() + ( 7 *60*60*1000))
            else (a=tw.getTime());
            tw.setTime(a);
            var tahun= tw.getFullYear ();
            // var hari= tw.getDay ();
            var bulan= tw.getMonth ();
            var tanggal= tw.getDate ();
            // var hariarray=new Array("Minggu,","Senin,","Selasa,","Rabu,","Kamis,","Jum'at,","Sabtu,");
            var bulanarray=new Array("Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","Nopember","Desember");
            document.getElementById("tanggalwaktu").innerHTML = tanggal+" "+bulanarray[bulan]+" "+tahun;
        </script>
        <p>Indira Regita Anansyah</p>
    </div>

</body>
</html>

resources/views/Book/form.blade.php
@php
if (isset($object)) {
$viewData = [
'title' => 'Edit buku',
'breadcrumbs' => [
'Buku',
$object->email,
'Edit',
],
];
} else {
$viewData = [
'title' => 'Tambah Buku',
'breadcrumbs' => [
'Buku',
'Tambah',
]
];
}
@endphp

@extends('layouts.app', $viewData)

@section('content')
{{-- Form Start --}}
@php
if (isset($object)) {
$actionUrl = route('buku.update', $object->id);
} else {
$actionUrl = route('buku.store');
}
@endphp
<div class="row">
  <div class="{{ isset($object) ? "col-md-8" : "col-md-12" }}">
    <form action="{{ $actionUrl }}" method="POST" enctype="multipart/form-data">

      @if (isset($object))
      {{ method_field('PATCH') }}
      <input type="hidden" name="user_id" value="{{ $object->id }}" />
      @endif

      {{ csrf_field() }}

      <div class="card">
        <div class="card-header">
          <h4 class="card-title">{{ $viewData['title'] }}</h4>
        </div>
        <br>
        <div class="card-body">
          <div class="form-body">
            <div class="row">

            <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Judul</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative has-icon-left">
                      <input type="text" class="form-control" name="judul" value="{{ isset($object) ? $object->judul : old('judul') }}" placeholder="Judul" required>
                      <div class="form-control-position">
                        <i class="feather icon-type"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Penerbit</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative has-icon-left">
                      <input type="text" class="form-control" name="penerbit" value="{{ isset($object) ? $object->penerbit : old('penerbit') }}" placeholder="Nama Penerbit" required>
                      <div class="form-control-position">
                        <i class="feather icon-user"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Penulis</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative has-icon-left">
                      <input type="text" class="form-control" name="penulis" value="{{ isset($object) ? $object->penulis : old('penulis') }}" placeholder="Nama Penulis" required>
                      <div class="form-control-position">
                        <i class="feather icon-user"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Sinopsis</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative">
                      <textarea name="sinopsis" class="form-control" placeholder="Sinopsis" required>{{ isset($object) ? $object->sinopsis : old('sinopsis') }}</textarea>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Kategori Buku </span>
                  </div>
                  <div class="col-md-10">
                    <select class="form-control select2" name="kategori_id">
                    @php
                    $old = isset($object) ? $object->kategori_id : old('kategori_id');
                    @endphp
                      <option value=""> -- Pilih Kategori -- </option>
                      @foreach ($kategori as $item)
                      <option value="{{ $item->id }}" {{ $old == $item->id ? 'selected' : '' }}>{{ $item->nama }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Tahun Terbit</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative has-icon-left">
                      <input type="month" class="form-control" name="thn_terbit" value="{{ isset($object) ? $object->thn_terbit : old('thn_terbit') }}" placeholder="YYYY" min="2000" max="2100" required>
                      <div class="form-control-position">
                        <i class="feather icon-calendar"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Jumlah Buku</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative has-icon-left">
                      <input type="number" class="form-control" name="jumlah_buku" value="{{ isset($object) ? $object->jumlah_buku : old('jumlah_buku') }}" placeholder="Jumlah Buku" required>
                      <div class="form-control-position">
                        <i class="feather icon-calendar"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Kondisi Buku </span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative">
                      <select class="form-control select2" id="kondisi" name="kondisi" required>
                        <option value="" required> -- Pilih Kondisi Buku -- </option>
                        @foreach (config('general.kondisi') as $key => $item)
                        <option value="{{ $key }}" {{isset($object) && $object->kondisi == $key ? 'selected' : ''}}>{{ $item['label'] }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Cover Buku</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" name="cover_buku">
                        <label class="custom-file-label" for="inputGroupFile01">Choose image</label>
                        @if (isset($object) && $object->file_url)
                        <small>Kosongkan jika tidak ingin mengupdate, lihat <a href="{{ $object->cover_buku_url }}" target="_blank">File Sebelumnya <span class="fa fa-external-link"></span></a></small>
                        @endif
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-2">
                    <span>Buku</span>
                  </div>
                  <div class="col-md-10">
                    <div class="position-relative">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile02" name="baca_buku">
                        <label class="custom-file-label" for="inputGroupFile02">Choose File</label>
                        @if (isset($object) && $object->file_url)
                        <small>Kosongkan jika tidak ingin mengupdate, lihat <a href="{{ $object->baca_buku_url }}" target="_blank">File Sebelumnya <span class="fa fa-external-link"></span></a></small>
                        @endif
                      </div>
                      <small>Jangan menambahkan E-Book jika buku tersebut memiliki hak cipta</small>
                    </div>
                  </div>
                </div>
              </div>


              <div class="col-md-2">
              </div>
              <div class="col-md-10">
                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Simpan</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

</div>

@endsection

resources/views/Book/index.blade.php
@extends('layouts.app', [
'title' => 'Buku',
'breadcrumbs' => [
'Buku', 
],
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">

            @if(isset($table['create']))

            @can('create buku')
            <a href="{{ $table['create']['url'] }}" class="btn btn-primary"><span class="fa fa-plus"></span> {{ $table['create']['label'] }}</a>
            @endcan

            @endif

            <!-- ========================================================================================== -->
            
            @if (auth()->user()->name == "Admin")
                <a href="{{ route('cetak-buku') }}" target="_blank" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
            @endif
            @if (auth()->user()->name == "Pustakawan")
                <a href="{{ route('cetak-buku') }}" target="_blank" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
            @endif
            <div class="table-responsive">
                <table class="table table-hover-animation nowrap scroll-horizontal-vertical" id="crudTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Kode Buku</th>
                            <th>Judul</th>
                            <th>Kategori Buku </th>
                            <th>Cover Buku</th>
                            <th>Download Buku</th>
                            <th>Jumlah Buku</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
// AJAX DataTable
var table = $('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    ajax: { 
        url: '{!! route('buku.data',) !!}',
    },
    ordering: false,
    columns: [
        { data: 'formatted_id', name: 'formatted_id' },
        { data: 'kode', name: 'kode' },
        { data: 'judul', name: 'judul' },
        { data: 'kategori_name', name: 'kategori_id' },
        { data: 'cover_buku_url', name: 'cover_buku_url' },
        { data: 'baca_buku_url', name: 'baca_buku_url' },
        { data: 'jumlah_buku', name: 'jumlah_buku' },
        { data: 'action', name: 'action' },
    ],
    drawCallback: function() {
        // Delete Confirmation
        $(".delete").on("click", function() {
            var form = $(this).parent().find("form");
            Swal.fire({
                title: 'Are you sure?',
                text: "Are you sure to delete this?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.value) {
                    form.submit();
                }
            })
        });
    }
});

//filter Berdasarkan satuan product
$('.filter-satuan').change(function () {
        table.column( $(this).data('column'))
        .search( $(this).val() )
        .draw();
    });


</script>
@endpush