routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('menu');
});

route::get('/menu', 'PagesController@index')->name('menu');
route::get('/beranda', 'PagesController@beranda')->name('beranda');
Route::get('/detailbuku', 'PagesController@detail')->name('detailbuku');
Route::get('/buku/setKategori', 'PagesController@setKategori')->name('setKategori');
Route::get('/detailbuku/{id}','PagesController@show')->name('show');
Route::get('/sisa','PagesController@sisa')->name('sisa');

route::get('/buku', 'PagesController@buku')->name('buku');

Route::resource('/pages', 'PagesController');
Route::get('/buku/cari','PagesController@cari')->name('cari');
Route::get('/info','PagesController@info')->name('info');
Route::get('/buku/kategori','PagesController@kategori')->name('kategori');
Route::get('/userguide','PagesController@guide')->name('guide');

Route::get('/laporan/cari','TransaksiController@cari')->name('cari');

Auth::routes();
route::get('logout', 'Auth\LoginController@logout')->name('logout');
route::get('/admin/user', 'Admin\UserController@create')->name('register');
route::post('/auth/login', 'RegisterController@store')->name('registerPost');
route::get('/auth/regis', 'Auth\LoginController@register')->name('regis');

Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::patch('profile', 'ProfileController@update')->name('profile.update');
});

route::middleware('admin')->group(function () {
    route::get('/home', 'HomeController@index')->name('home');
    route::get('/histori', 'TransaksiController@histori')->name('histori');

    route::get('/laporanpengembalian/periode', 'TransaksiController@periodepengembalian')->name('periode_awal');
    route::get('/laporan/periode', 'TransaksiController@periodepinjam')->name('periode_awal');

    // ASC & DESC
    route::get('/laporan/dataterbaru', 'TransaksiController@baru')->name('baru');
    route::get('/laporan/dataterlama', 'TransaksiController@lama')->name('lama');
    route::get('/histori/dataterbaru', 'TransaksiController@databaru')->name('baru');
    route::get('/histori/dataterlama', 'TransaksiController@datalama')->name('lama');

    // Filter Laporan
    route::get('/pinjam', 'TransaksiController@pinjam')->name('pinjam');
    route::get('/cetaklaporan', 'TransaksiController@cetakLaporan')->name('cetaklaporan');
    route::get('/cetaklaporanpertanggal/{tglawal}/{tglakhir}', 'TransaksiController@cetakLaporanPertanggal')->name('cetaklaporanpertanggal');
    Route::get('/laporan/periode','Transaksicontroller@periode')->name('periode');


    Route::prefix('acl')->name('acl.')->group(function () {
        Route::get('permission', 'Admin\ACLController@permissionList')->name('permission.index');
        Route::get('permission/data', 'Admin\ACLController@permissionData')->name('permission.data');
        Route::prefix('role')->name('role.')->group(function () {
            Route::get('/', 'Admin\ACLController@roleList')->name('index');
            Route::get('/data', 'Admin\ACLController@roleData')->name('data');
            Route::get('/create', 'Admin\ACLController@createRole')->name('create');
            Route::post('/create', 'Admin\ACLController@storeRole')->name('store');
            Route::get('/{id}/edit', 'Admin\ACLController@editRole')->name('edit');
            Route::patch('/{id}/edit', 'Admin\ACLController@updateRole')->name('update');
            Route::delete('/{id}/destroy', 'Admin\ACLController@deleteRole')->name('destroy');
        });
    });

    // Users
    route::resource('/users', 'Admin\UserController');
    route::get('/users/data/json', 'Admin\UserController@getData')->name('users.data');

    // Buku
    Route::resource('/buku', 'BukuController');
    Route::get('/buku/data/json', 'BukuController@getData')->name('buku.data');
    Route::post('/buku/data/json', 'BukuController@imageUploadPost')->name('image.upload.post');
    Route::post('/buku/data/json', 'BukuController@bacaUploadPost')->name('baca.upload.post');
    Route::get('/cetak-buku', 'BukuController@cetak')->name('cetak-buku');

    // Anggota
    Route::resource('/anggota', 'AnggotaController');
    Route::get('/anggota/data/json', 'AnggotaController@getData')->name('anggota.data');
    Route::get('/cetak-anggota', 'AnggotaController@cetak')->name('cetak-anggota');

    // Kategori
    Route::resource('/kategori', 'KategoriController');
    Route::get('/kategori/data/json', 'KategoriController@getData')->name('kategori.data');

    // Transaksi
    Route::resource('/transaksi', 'TransaksiController');
    Route::get('/transaksi/data/json', 'TransaksiController@getData')->name('transaksi.data');
    Route::get('/cetak-transaksi', 'TransaksiController@cetak')->name('cetak-transaksi');

});

Route::get('check/accessor', function (App\Models\Transaksi $id) {
    $data = new \App\Models\Transaksi;
    dd($data->first()->getBorrowDateAttribute());
});

app/Models/Transaksi.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transaksi extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'kode',
        // 'kode_buku',
        'buku_id',
        'user_id',
        // 'kode_anggota',
        'anggota_id',
        'tgl_pinjam',
        'tgl_hrs_kembali',
        'tgl_pengembalian',
    ];

    /**
     * Get formatted ID.
     *
     * @return string
     */
    public function getFormattedIdAttribute()
    {
        return '#' . $this->attributes['id'];
    }

    public static function boot()
    {
        parent::boot();

        static::created(function($model) {
            $model->kode = 'TR'.Carbon::now()->format('YmdHms').$model->id;
            $model->save();
        });
    }

    /**
     * Relation to anggota
     *
     * @return BelongsTo
     */
    public function anggota()
    {
        return $this->belongsTo(\App\Models\Anggota::class, 'anggota_id', 'id');
    }

    
    /**
     * Get Nama Anggota
     * 
     * @return string
     */
    public function getAnggotaNameAttribute()
    {
        // return optional($this->anggota()->first('nama'))->first();
        $anggota = $this->anggota()->first(['name']);
        
        if (!is_null($anggota)) {
            return $anggota->name;
        }
        
        return '-';
    }

    /**
     * Relation to buku
     *
     * @return BelongsTo
     */
    public function buku()
    {
        return $this->belongsTo(\App\Models\Buku::class, 'buku_id', 'id');
    }

    /**
     * Get Judul Buku
     * 
     * @return string
     */
    public function getBukuNameAttribute()
    {
        // return optional($this->buku())->first('judul');

        $buku = $this->buku()->first(['judul']);

        if (!is_null($buku)) {
            return $buku->judul;
        }

        return '-';
    }

    /**
     * Get Return Date
     * 
     * @return string
     */
    public function getReturnDateAttribute()
    {
        $now = Carbon::now();
        if ($now->format('Y-m-d') > $this->getAttribute('tgl_hrs_kembali')) {
            return '<div class="chip chip-' . 'danger' . '">
                    <div class="chip-body"><div class="chip-text">' . 
                    $this->getAttribute('tgl_hrs_kembali') . 
                    '</div></div></div>';
        }

        return $this->getAttribute('tgl_hrs_kembali');
    }

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }

    public function getUserNameAttribute()
    {
        // return optional($this->anggota()->first('nama'))->first();
        $user = $this->user()->first(['name']);
        
        if (!is_null($user)) {
            return $user->name;
        }
        
        return '-';
    }

}

resources/views/laporan/cetak-peminjaman.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <style>
        table.static {
            position: relative;
            border: 1px solid #543535;
        }
    </style>
    <title>Cetak Data Laporan Peminjaman</title>
</head>
<body>
    <div class="form-group">
        <div class="container">
            <div class="row">
                <center><img src="/img/logo.png" style="max-width: 150px;" class="inline"></center>
                <center><img src="/img/logo1.jpeg" style="max-width: 150px;" class="inline"></center>
            </div>
        </div>
        <hr>
        <h3><center>Data Laporan Peminjaman dan Pengembalian</center></h3>
        <table class="static" align="center" rules="all" border="1px" style="width: 95%;">
            <tr>
                <th>No</th>
                <th>Kode Transaksi</th>
                <th>Judul Buku</th>
                <th>Nama User Anggota</th>
                <th>Tanggal Peminjaman</th>
                <th>Batas Waktu Pengembalian</th>
                <th>Tanggal Pengembalian</th>
            </tr>
            @foreach($data as $data)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $data->kode }}</td>
                <td>{{ $data->buku_name }}</td>
                <td>{{ $data->user_name }}</td>
                <td>{{ $data->tgl_pinjam }}</td>
                <td>{{ $data->tgl_hrs_kembali }}</td>
                @if($data->deleted_at == null)
                <td>Belum Dikembalikan!</td>
                @else
                <td>{{ date('d F Y', strtotime($data->deleted_at)) }}</td>
                @endif
            </tr>
            @endforeach
        </table>
    </div>
    <br>
    <br>

    <script type="text/javascript">
    window.print();
    
    </script>

    <div class="container" style="text-align: right;">
        <p>Bandung,<span id="tanggalwaktu"></span></p>
        <br><br>
        <script>
            var tw = new Date();
            if (tw.getTimezoneOffset() == 0) (a=tw.getTime() + ( 7 *60*60*1000))
            else (a=tw.getTime());
            tw.setTime(a);
            var tahun= tw.getFullYear ();
            // var hari= tw.getDay ();
            var bulan= tw.getMonth ();
            var tanggal= tw.getDate ();
            // var hariarray=new Array("Minggu,","Senin,","Selasa,","Rabu,","Kamis,","Jum'at,","Sabtu,");
            var bulanarray=new Array("Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","Nopember","Desember");
            document.getElementById("tanggalwaktu").innerHTML = tanggal+" "+bulanarray[bulan]+" "+tahun;
        </script>
        <p>Indira Regita Anansyah</p>
    </div>

</body>
</html>

resources/views/laporan/cetak-pengembalian.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <style>
        table.static {
            position: relative;
            border: 1px solid #543535;
        }
    </style>
    <title>Cetak Data Laporan Pengembalian</title>
</head>
<body>
    <div class="form-group">
        <div class="container">
            <div class="row">
                <center><img src="/img/logo.png" style="max-width: 150px;" class="inline"></center>
                <center><img src="/img/logo1.jpeg" style="max-width: 150px;" class="inline"></center>
            </div>
        </div>
        <hr>
        <h3><center>Data Laporan Pengembalian</center></h3>
        <table class="static" align="center" rules="all" border="1px" style="width: 95%;">
            <tr>
                <th>No</th>
                <th>Kode Transaksi</th>
                <th>Judul Buku</th>
                <th>Nama Anggota</th>
                <th>Tanggal Peminjaman</th>
                <th>Batas Waktu Pengembalian</th>
                <th>Tanggal Kembali</th>
            </tr>
            @foreach($dataa as $data)
            <tr>
                <th>{{ $loop->iteration }}</th>
                <td>{{ $data->kode }}</td>
                <td>{{ $data->buku_name }}</td>
                <td>{{ $data->anggota_name }}</td>
                <td>{{ $data->tgl_pinjam }}</td>
                <td>{{ $data->tgl_hrs_kembali }}</td>
                <td>{{ $data->deleted_at }}</td>
            </tr>
            @endforeach
        </table>
    </div>
    <br>
    <br>

    <script type="text/javascript">
    window.print();
    
    </script>

    <div class="container" style="text-align: right;">
        <p>Bandung,<span id="tanggalwaktu"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        <!-- <p>TTD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p> -->
        <img src="img/ttd2.jpeg" alt="" style="width: 200px; height: 100px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <script>
            var tw = new Date();
            if (tw.getTimezoneOffset() == 0) (a=tw.getTime() + ( 7 *60*60*1000))
            else (a=tw.getTime());
            tw.setTime(a);
            var tahun= tw.getFullYear ();
            // var hari= tw.getDay ();
            var bulan= tw.getMonth ();
            var tanggal= tw.getDate ();
            // var hariarray=new Array("Minggu,","Senin,","Selasa,","Rabu,","Kamis,","Jum'at,","Sabtu,");
            var bulanarray=new Array("Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","Nopember","Desember");
            document.getElementById("tanggalwaktu").innerHTML = tanggal+" "+bulanarray[bulan]+" "+tahun;
        </script>
        <p>Indira Regita Anansyah&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
    </div>

</body>
</html>

resources/views/laporan/peminjaman.blade.php
@extends('layouts.app', [
'title' => 'Laporan Peminjaman',
'breadcrumbs' => [
'Laporan',
'peminjaman',
'List',
],
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">

            @if (auth()->user()->name == "Ketua")
                <a href="{{ route('cetak-peminjaman') }}" target="_blank" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
            @endif
            @if (auth()->user()->name == "Admin")
                <a href="{{ route('cetak-peminjaman') }}" target="_blank" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
            @endif
            <div class="table-responsive">
                <table class="table table-hover-animation nowrap scroll-horizontal-vertical" id="crudTable">
                    <thead>
                        <tr>
                            @foreach($table['columns'] as $column)
                            <th>{{ $column['label'] }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
$('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    ajax: '{{ $table['table_url'] }}',
    ordering: false,
    columns: [
        @foreach($table['columns'] as $column) {
            data: '{{ $column['name'] }}',
            name: '{{ $column['name'] }}'
        },
        @endforeach
    ],
    drawCallback: function() {
        // Delete Confirmation
        $(".delete").on("click", function() {
            var form = $(this).parent().find("form");
            Swal.fire({
                title: 'Are you sure?',
                text: "Are you sure to delete this?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.value) {
                    form.submit();
                }
            })
        });
    }
});
</script>
@endpush

resources/views/laporan/pengembalian.blade.php
@extends('layouts.app', [
'title' => 'Laporan Pengembalian',
'breadcrumbs' => [
'Laporan',
'Pengembalian',
'List',
],
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">

            @if (auth()->user()->name == "Ketua")
                <a href="{{ route('cetak-pengembalian') }}" target="_blank" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
            @endif
            @if (auth()->user()->name == "Admin")
                <a href="{{ route('cetak-pengembalian') }}" target="_blank" class="btn btn-primary"><span class="fa fa-print"></span> Cetak</a>
            @endif
            <div class="table-responsive">
                <table class="table table-hover-animation nowrap scroll-horizontal-vertical" id="crudTable">
                    <thead>
                        <tr>
                            @foreach($table['columns'] as $column)
                            <th>{{ $column['label'] }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
$('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    ajax: '{{ $table['table_url'] }}',
    ordering: false,
    columns: [
        @foreach($table['columns'] as $column) {
            data: '{{ $column['name'] }}',
            name: '{{ $column['name'] }}'
        },
        @endforeach
    ],
    drawCallback: function() {
        // Delete Confirmation
        $(".delete").on("click", function() {
            var form = $(this).parent().find("form");
            Swal.fire({
                title: 'Are you sure?',
                text: "Are you sure to delete this?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.value) {
                    form.submit();
                }
            })
        });
    }
});
</script>
@endpush