routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('menu');
});

route::get('/menu', 'PagesController@index')->name('menu');
route::get('/beranda', 'PagesController@beranda')->name('beranda');
Route::get('/detailbuku', 'PagesController@detail')->name('detailbuku');
Route::get('/buku/setKategori', 'PagesController@setKategori')->name('setKategori');
Route::get('/detailbuku/{id}','PagesController@show')->name('show');
Route::get('/sisa','PagesController@sisa')->name('sisa');

route::get('/buku', 'PagesController@buku')->name('buku');

Route::resource('/pages', 'PagesController');
Route::get('/buku/cari','PagesController@cari')->name('cari');
Route::get('/info','PagesController@info')->name('info');
Route::get('/buku/kategori','PagesController@kategori')->name('kategori');
Route::get('/userguide','PagesController@guide')->name('guide');

Route::get('/laporan/cari','TransaksiController@cari')->name('cari');

Auth::routes();
route::get('logout', 'Auth\LoginController@logout')->name('logout');
route::get('/admin/user', 'Admin\UserController@create')->name('register');
route::post('/auth/login', 'RegisterController@store')->name('registerPost');
route::get('/auth/regis', 'Auth\LoginController@register')->name('regis');

Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::patch('profile', 'ProfileController@update')->name('profile.update');
});

route::middleware('admin')->group(function () {
    route::get('/home', 'HomeController@index')->name('home');
    route::get('/histori', 'TransaksiController@histori')->name('histori');

    route::get('/laporanpengembalian/periode', 'TransaksiController@periodepengembalian')->name('periode_awal');
    route::get('/laporan/periode', 'TransaksiController@periodepinjam')->name('periode_awal');

    // ASC & DESC
    route::get('/laporan/dataterbaru', 'TransaksiController@baru')->name('baru');
    route::get('/laporan/dataterlama', 'TransaksiController@lama')->name('lama');
    route::get('/histori/dataterbaru', 'TransaksiController@databaru')->name('baru');
    route::get('/histori/dataterlama', 'TransaksiController@datalama')->name('lama');

    // Filter Laporan
    route::get('/pinjam', 'TransaksiController@pinjam')->name('pinjam');
    route::get('/cetaklaporan', 'TransaksiController@cetakLaporan')->name('cetaklaporan');
    route::get('/cetaklaporanpertanggal/{tglawal}/{tglakhir}', 'TransaksiController@cetakLaporanPertanggal')->name('cetaklaporanpertanggal');
    Route::get('/laporan/periode','Transaksicontroller@periode')->name('periode');


    Route::prefix('acl')->name('acl.')->group(function () {
        Route::get('permission', 'Admin\ACLController@permissionList')->name('permission.index');
        Route::get('permission/data', 'Admin\ACLController@permissionData')->name('permission.data');
        Route::prefix('role')->name('role.')->group(function () {
            Route::get('/', 'Admin\ACLController@roleList')->name('index');
            Route::get('/data', 'Admin\ACLController@roleData')->name('data');
            Route::get('/create', 'Admin\ACLController@createRole')->name('create');
            Route::post('/create', 'Admin\ACLController@storeRole')->name('store');
            Route::get('/{id}/edit', 'Admin\ACLController@editRole')->name('edit');
            Route::patch('/{id}/edit', 'Admin\ACLController@updateRole')->name('update');
            Route::delete('/{id}/destroy', 'Admin\ACLController@deleteRole')->name('destroy');
        });
    });

    // Users
    route::resource('/users', 'Admin\UserController');
    route::get('/users/data/json', 'Admin\UserController@getData')->name('users.data');

    // Buku
    Route::resource('/buku', 'BukuController');
    Route::get('/buku/data/json', 'BukuController@getData')->name('buku.data');
    Route::post('/buku/data/json', 'BukuController@imageUploadPost')->name('image.upload.post');
    Route::post('/buku/data/json', 'BukuController@bacaUploadPost')->name('baca.upload.post');
    Route::get('/cetak-buku', 'BukuController@cetak')->name('cetak-buku');

    // Anggota
    Route::resource('/anggota', 'AnggotaController');
    Route::get('/anggota/data/json', 'AnggotaController@getData')->name('anggota.data');
    Route::get('/cetak-anggota', 'AnggotaController@cetak')->name('cetak-anggota');

    // Kategori
    Route::resource('/kategori', 'KategoriController');
    Route::get('/kategori/data/json', 'KategoriController@getData')->name('kategori.data');

    // Transaksi
    Route::resource('/transaksi', 'TransaksiController');
    Route::get('/transaksi/data/json', 'TransaksiController@getData')->name('transaksi.data');
    Route::get('/cetak-transaksi', 'TransaksiController@cetak')->name('cetak-transaksi');

});

Route::get('check/accessor', function (App\Models\Transaksi $id) {
    $data = new \App\Models\Transaksi;
    dd($data->first()->getBorrowDateAttribute());
});

app/Http/Controllers/Admin/ACLController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Permission;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Http\Controllers\Controller;
use App\Http\Requests\RoleRequest;
use Spatie\Permission\Models\Role;

class ACLController extends Controller
{
    /**
     * Get permission list page.
     *
     * @return View
     */
    public function permissionList()
    {
        return view('acl.permission-list');
    }

    /**
     * Get JSON data for table.
     *
     * @return Response
     */
    public function permissionData()
    {
        $query = Permission::orderBy('id', 'desc')->select([
            'id', 
            'name', 
        ]);

        return Datatables::of($query)->addColumn('has_role', function($item){
            return $item->roles->pluck('name')->implode(', ');
        })->make();
    }

    /**
     * Show role list page.
     *
     * @return View
     */
    public function roleList()
    {
        return view('acl.role-list');
    }

    /**
     * Role JSON Data for Table.
     *
     * @return Response
     */
    public function roleData()
    {
        $query = Role::orderBy('id', 'desc')->select([
            'id', 
            'name', 
        ]);

        return Datatables::of($query)->addColumn('action', function($item){
            $string = '';
            
            if ($item->name != config('permission.super_admin')) {
                $string = '<a href="' . route('acl.role.edit', $item->id) . '"><button title="Edit" class="btn btn-icon btn-sm btn-success waves-effect waves-light" style="margin-right: 5px;"><i class="fa fa-pencil"></i></button></a>';
                $string .= '<button title="Hapus" class="btn btn-icon btn-sm btn-danger waves-effect waves-light delete"><i class="fa fa-trash"></i></button>';
                $string .= '<form action="' . route('acl.role.destroy', $item->id) . '" method="POST">' . method_field('delete') . csrf_field() . '</form>';
            }

            return $string;
        })->rawColumns(['action'])->make();
    }

    /**
     * Show create role form.
     *
     * @return View
     */
    public function createRole()
    {
        $data['permissions'] = Permission::whereNull('parent_id')->get(['id', 'name']);

        return view('acl.role-form', $data);
    }

    /**
     * Show edit role form.
     *
     * @return View
     */
    public function editRole()
    {
        $data['permissions'] = Permission::whereNull('parent_id')->get(['id', 'name']);
        $data['object'] = Role::findOrFail(request()->id);

        return view('acl.role-form', $data);
    }

    /**
     * Update role.
     *
     * @param RoleRequest $request
     * 
     * @return Response
     */
    public function updateRole(RoleRequest $request)
    {
        $posted = $request->all();
        $role = Role::findOrFail(request()->id);

        \DB::transaction(function() use($posted, $role) {
            $role->update([
                'name' => $posted['name']
            ]);

            $role->permissions()->detach();
            if (isset($posted['permissions']) && count($posted['permissions']) > 0) {
                foreach ($posted['permissions'] as $permissionId) {
                    $role->givePermissionTo(intval($permissionId));
                }
            }
        });

        return redirect()->back()->with('status', 'Role berhasil disimpan.');
    }

    /**
     * Store Role to Database.
     *
     * @param RoleRequest $request
     * 
     * @return Response
     */
    public function storeRole(RoleRequest $request)
    {
        $posted = $request->all();
        \DB::transaction(function() use($posted) {
            $role = Role::create([
                'name' => $posted['name']
            ]);
            if (isset($posted['permissions']) && count($posted['permissions']) > 0) {
                foreach ($posted['permissions'] as $permissionId) {
                    $role->givePermissionTo(intval($permissionId));
                }
            }
        });

        return redirect()->back()->with('status', 'Role berhasil dibuat.');
    }

    /**
     * Delete role.
     *
     * @return Response
     */
    public function deleteRole()
    {
        $role = Role::findOrFail(request()->id);
        $role->delete();

        return redirect()->back()->with('status', 'Role berhasil dihapus.');
    }
}

resources/views/acl/permission-list.blade.php
@extends('layouts.app', [
    'title' => 'Daftar Permission',
    'breadcrumbs' => [
        'Permission',
        'List',
    ]
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover-animation nowrap scroll-horizontal-vertical" id="crudTable">
                    <thead>
                        <tr>
                            <th>Nama Permission</th>
                            <th>Dimiliki oleh Role</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
var datatable = $('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    ajax: {
        url: '{!! route('acl.permission.data') !!}',
    },
    ordering: false,
    columns: [
        { data: 'name', name: 'name' },
        { data: 'has_role', name: 'has_role' },
    ]
});
</script>
@endpush

resources/views/acl/role-form.blade.php
@php
if (isset($object)) {
    $viewData = [
        'title' => 'Edit Role',
        'breadcrumbs' => [
            'Dashboard',
            'Role',
            $object->name,
            'Edit'
        ],
    ];
} else {
    $viewData = [
        'title' => 'Tambah Role',
        'breadcrumbs' => [
            'Dashboard',
            'Role',
            'Tambah'
        ],
    ];
}
@endphp

@extends('layouts.app', $viewData)

@section('content')
<div class="card">
    <div class="card-header">
        <h4 class="card-title">{{ $viewData['title'] }}</h4>
    </div>
    <br>
    <div class="card-body">
            @php
            if (isset($object)) {
                $actionUrl = route('acl.role.update', [
                    'id' => $object->id,
                ]);
            } else {
                $actionUrl = route('acl.role.store');
            }
            
            @endphp
            <form class="form form-horizontal" method="POST" action="{{ $actionUrl }}" enctype="multipart/form-data">
                @csrf
                @if (isset($object))
                {{ method_field('PATCH') }}
                @endif
                <div class="form-body">
                    <div class="row">

                        <div class="col-12">
                            <div class="form-group row">
                                <div class="col-md-2">
                                    <span>Nama Role</span>
                                </div>
                                <div class="col-md-10">
                                    <div class="position-relative has-icon-left">
                                        <input type="text" class="form-control" name="name" value="{{ isset($object) ? $object->name : old('name') }}" placeholder="Nama Role" autofocus>
                                        <div class="form-control-position">
                                            <i class="feather icon-user"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group row">
                                <div class="col-md-2">
                                    <span>Permission</span>
                                </div>
                                <div class="col-md-10">
                                    <div class="custom-control custom-checkbox roles">
                                        <input type="checkbox" class="custom-control-input" name="permission_all" id="permission_all" value="permission_all">
                                        <label class="custom-control-label" for="permission_all">Check All</label>
                                    </div>
                                    <br>
                                    <div class="row">
                                        @foreach ($permissions as $permission)
                                        <div class="col-sm-12 permissions">
                                            <!-- Default unchecked -->
                                            <div class="custom-control custom-checkbox">
                                                <input type="checkbox" class="custom-control-input parent" name="permissions[]" id="{{ str_slug($permission->name) }}" value="{{ $permission->id }}" {{ isset($object) && $object->permissions->pluck('name')->contains($permission->name) ? 'checked' : '' }}>
                                                <label class="custom-control-label" for="{{ str_slug($permission->name) }}"><strong>{{ $permission->name }}</strong></label>
                                            </div>
                                            <br>
                                            @if ($permission->childs()->count() > 0)
                                                <div class="row mb-2 {{ str_slug($permission->name) }}">
                                                    @foreach ($permission->childs as $child)
                                                    <div class="col-md-4">
                                                        <div class="custom-control custom-checkbox">
                                                            <input type="checkbox" class="custom-control-input" name="permissions[]" id="{{ $child->id }}" value="{{ $child->id }}" {{ isset($object) && $object->permissions->pluck('name')->contains($child->name) ? 'checked' : '' }}>
                                                            <label class="custom-control-label" for="{{ $child->id }}">{{ $child->name }}</label>
                                                        </div>
                                                    </div>
                                                    @endforeach
                                                </div>
                                            @endif
                                        </div>
                                        <hr>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>

                        

                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
    </div>
</div>
@endsection

@push('after_scripts')
<script>
$('#permission_all').change(function() {
    if($(this).is(":checked")) {
        $('.permissions input').not(this).prop('checked', true);
    } else {
        $('.permissions input').not(this).prop('checked', false);
    }       
});
$('.parent').change(function() {
    if($(this).is(":checked")) {
        $(this).parent().parent().find('input[type=checkbox]').prop('checked', true);
    } else {
        $(this).parent().parent().find('input[type=checkbox]').prop('checked', false);
    }      
});
</script>
@endpush

resources/views/acl/role-list.blade.php
@extends('layouts.app', [
    'title' => 'Daftar Role',
    'breadcrumbs' => [
        'Role',
        'List',
    ]
])

@section('content')
<a href="{{ route('acl.role.create') }}" class="btn btn-primary mb-1"><span class="fa fa-plus"></span> Tambah Role</a>
<div class="card">
    <div class="card-content">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover-animation nowrap scroll-horizontal-vertical" id="crudTable">
                    <thead>
                        <tr>
                            <th>Nama Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/forms/select/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/forms/select/select2.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
var datatable = $('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    ajax: {
        url: '{!! route('acl.role.data') !!}',
    },
    ordering: false,
    columns: [
        { data: 'name', name: 'name' },
        { data: 'action', name: 'action' },
    ],
    drawCallback: function(){
        // Delete Confirmation
        $(".delete").on("click", function(){
            var form = $(this).parent().find("form");
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Yakin ingin menghapus ini?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya!'
            }).then((result) => {
                if (result.value) {
                    form.submit();
                }
            })
        });
    }
});
</script>
@endpush